---
title: "EA Market testing data analysis"
author: "David Reinstein and other members of the EAMT team"
logo: bulb.png
bibliography: references.bib
csl: assets/apa.csl
link-citations: true
always_allow_html: true
use_littlefoot: true
sidebar_width: "350px"
site: bookdown::bookdown_site
output:
  rethinkpriorities::book:
    toc_depth: 2
    split_by: "chapter"
github-repo: daaronr/eamt_data_analysis
description: "Description and analysis of EAMT trials"
---


```{r html, echo=FALSE}
# globally set chunk options
#This allows building even if errors come along the way
knitr::opts_chunk$set(fig.align='center', out.width='80%', warning=FALSE, message = FALSE, error=TRUE)

my_output <- knitr::opts_knit$get("rmarkdown.pandoc.to")

```

# About {.unnumbered}

See ['Effective Giving & Action: Market testing & Synthesis' - public](https://effective-giving-marketing.gitbook.io/untitled/) and [private version](https://app.gitbook.com/o/-MfFk4CTSGwVOPkwnRgx/s/-Mf8cHxdwePMZXRTKnEE/)


## Tech and collophon

This is styled based on the Rethink Priorities '[Bookdown template](https://rethinkpriorities.github.io/bookdown-template)' ...  and you may wish to manually update from there

Note that this is a 'bookdown site in the gitbook style'. However, we're not sure yet if and how it can be integrated with the `https://app.gitbook.com/` content.


```{r}

library(pacman)
p_load(dplyr, knitr, here, bookdown, install = FALSE)
p_load(readxl)
p_load(pryr)
p_load(stringr)
p_load(kableExtra)
p_load(devtools)
p_load(googledrive)
p_load(googlesheets4)
devtools::install_github("paulhendricks/anonymizer")
library(anonymizer)


devtools::install_github("rethinkpriorities/rp-r-package")
library(rethinkpriorities)

devtools::install_github("rethinkpriorities/r-noodling-package")
library(rnoodling)

```




